development:
  adapter: postgresql
  database: guyra_development
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: guyra_test
  pool: 5
  timeout: 5000
  host: localhost

production:
  adapter: postgresql
  database: guyra_production
  pool: 5
  timeout: 5000
  host: localhost